Add 2fa user documentation
hitobito/user_documentation pull request #17
Opened 2022-01-11 14:59 UTC by TheWalkingLeek

refs: https://github.com/hitobito/hitobito/issues/1303

2022-01-14 18:49 UTC, olibrian commented on two_factor_authentication.rst
> +Für die zwei Faktor Authentifizierung wird ein Smartphone und die freeOTP App: https://freeotp.github.io/ benötigt. Zum Herunterladen der App benötigen Sie eine Internetverbindung und evtl. ein Konto
Ist freeOTP die einzige App oder gibt es auch noch Alternativen?

2022-01-17 07:02 UTC, TheWalkingLeek commented on two_factor_authentication.rst
> +Für die zwei Faktor Authentifizierung wird ein Smartphone und die freeOTP App: https://freeotp.github.io/ benötigt. Zum Herunterladen der App benötigen Sie eine Internetverbindung und evtl. ein Konto
Denke die meisten solchen Authenticator Apps werden funktionieren. Ich habs aber nur mit dieser App getestet

2022-01-17 15:12 UTC, olibrian approved these changes

2022-01-17 17:50 UTC, carlobeltrame requested changes

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Zwei Faktor Authentifizierung
```suggestion
Zwei-Faktor-Authentifizierung
```

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Hitobito unterstützt die Zwei Faktor Authentifizierung mit folgenden Methoden:
```suggestion
Hitobito unterstützt die Zwei-Faktor-Authentifizierung mit folgender Methode:
```

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +- TOTP mittels QR Code und sechsstelligem Code
```suggestion
- TOTP mittels Authenticator-App und sechsstelligem Code
```
Für die Nutzenden die nicht wissen was TOTP ist, ist es vermutlich eindeutiger, wenn wir über die App statt den QR-Code schreiben.

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Für die zwei Faktor Authentifizierung wird ein Smartphone und die freeOTP App: https://freeotp.github.io/ benötigt. Zum Herunterladen der App benötigen Sie eine Internetverbindung und evtl. ein Konto
```suggestion
Für die Zwei-Faktor-Authentifizierung wird ein Smartphone und eine Authenticator-App benötigt. Die Zwei-Faktor-Authentifizierung wurde mit der kostenfreien freeOTP App (https://freeotp.github.io/) entwickelt und getestet, sollte aber grundsätzlich auch mit anderen ähnlichen Apps wie Google Authenticator oder andOTP funktionieren.
```
Zum Herunterladen von Apps benötigt man immer eine Internetverbindung und ein Konto im App Store, das hat nichts mit dieser App zu tun.

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Um die zwei Faktor Authentifizierung einzurichten, müssen Sie sich erst in Hitobito anmelden. Navigieren Sie anschliessend mittels ihrem Namen als Link oben rechts auf ihr Profil. Sie sollten nun unt
```suggestion
Um die Zwei-Faktor-Authentifizierung einzurichten, muss man sich erst in Hitobito anmelden. Auf dem eigenen Profil kann man nun im Dropdown "Login" den Knopf "Zwei Faktor Authentifizierung einrichten" sehen. Durch Klicken auf diesen Knopf landet man auf einer Seite mit einem QR-Code.
```
Der Rest der user documentation ist in Du-Form geschrieben. Ich würde vorschlagen, Du oder Sie zu vermeiden wo möglich.

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Öffnen Sie nun die freeOTP App auf Ihrem Smartphone und drücken Sie auf den QR Code Knopf in der Kopfzeile der App. Nun öffnet sich die Kamera mit einem Quadrat in der Mitte. Scannen Sie den QR Code
```suggestion
In der freeOTP App auf dem Smartphone klickt man nun auf den QR-Code-Knopf in der Kopfzeile. Dadurch öffnet sich die Kamera mit einem Quadrat in der Mitte. Der QR-Code in hitobito kann nun mit der Kamera gescannt werden.
```

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Sobald der Code gescannt wurde, schliesst sich die Kamera und ein neues Element in der Liste sollte auf der App ersichtlich sein. Dies erkennen Sie anhand der Bezeichnung ''hitobito'' und ihrer E-Mai
```suggestion
Sobald der Code gescannt wurde, schliesst sich die Kamera und ein neues Element in der Liste sollte auf der App ersichtlich sein. Dies erkennt man anhand der Bezeichnung ''hitobito'' und der E-Mail-Adresse. Durch einen Klick auf den Eintrag wird ein sechsstelliger Code wird angezeigt.
```

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Dieser Code ändert sich alle paar Sekunden. Tippen Sie den Code in Hitobito ab und klicken Sie auf "Absenden". Sollte der Code inkorrekt sein, wird eine enstprechende Nachricht angezeigt und Sie müss
```suggestion
Dieser Code ändert sich alle paar Sekunden. Nun tippt man den Code in hitobito ein und klickt auf "Absenden". Sollte der Code inkorrekt sein, wird eine enstprechende Nachricht angezeigt und mann muss es erneut versuchen. Sobald der Code korrekt und rechtzeitig eingegeben wurde, wird man auf das Profil zurückgeleitet, und die Zwei-Faktor-Authentifizierung ist eingerichtet.
```

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Login mit zwei Faktor Authentifizierung
```suggestion
Login mit Zwei-Faktor-Authentifizierung
```

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Sobald Sie die zwei Faktor Authentifizierung eingerichtet haben, müssen Sie den Code auf der App bei jedem Login eingeben. Nach der Eingabe Ihrer E-Mail und Passwort werden Sie auf eine Seite mit ein
```suggestion
Sobald die Zwei-Faktor-Authentifizierung eingerichtet ist, muss der Code von der App bei jedem Login eingegeben werden. Nach der Eingabe von E-Mail und Passwort wird man auf eine Seite mit einer Eingabeaufforderung weitergeleitet. Hier tippt man nun wieder den Code aus der freeOTP App ab und klickt auf "Absenden". Sollte der Code nicht korrekt oder bereits abgelaufen sein, wird eine entsprechende Nachricht angezeigt. Ist der Code jedoch korrekt, wird man authentifiziert und in hitobito weitergeleitet.
```

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Zurücksetzen und Deaktivieren
```suggestion
Zurücksetzen und deaktivieren
```

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Admins können die Zwei Faktor Authentifizierung einer Person zurücksetzen oder deaktivieren, indem Sie auf das Profil einer Person navigieren. Dort erscheinen unter dem Dropdown "Login" zwei Knöpfe "
```suggestion
Administratoren können die Zwei-Faktor-Authentifizierung einer Person auf deren Profil zurücksetzen oder deaktivieren. Dort erscheinen unter dem Dropdown "Login" zwei Knöpfe "Zwei Faktor Authentifizierung zurücksetzen" und "Zwei Faktor Authentifizierung deaktivieren".
```
Aber wie im anderen PR bemerkt wäre ich dafür, dass das auch jeder User für sich selber darf. Das ist ja nötig wenn man mal das Handy wechselt. Wir haben ja keine Recovery Codes oder ähnliches.

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Wird die 2FA zurückgesetzt, wird der Nutzer beim nächsten Login einen neuen QR Code scannen müssen.
```suggestion
Wird die Zwei-Faktor-Authentifizierung zurückgesetzt, wird der Nutzer beim nächsten Login einen neuen QR Code scannen müssen.
```

2022-01-17 17:50 UTC, carlobeltrame commented on two_factor_authentication.rst
> +Bei der Deaktivierung wird der Nutzer nicht mehr zur 2FA aufgefordert.
```suggestion
Bei der Deaktivierung wird der Nutzer nicht mehr zur Zwei-Faktor-Authentifizierung aufgefordert.
```

2022-01-24 12:16 UTC, carlobeltrame approved these changes

2022-01-24 16:49 UTC, merged